export const mockData = {
  location: {
    cities: [
      {
        name: 'London',
        local_names: {
          ne: 'लन्डन',
          os: 'Лондон',
          yo: 'Lọndọnu',
          ku: 'London',
          ta: 'இலண்டன்',
          mi: 'Rānana',
          is: 'London',
          eu: 'Londres',
          kv: 'Лондон',
          rm: 'Londra',
          or: 'ଲଣ୍ଡନ',
          ie: 'London',
          ay: 'London',
          sc: 'Londra',
          ru: 'Лондон',
          hu: 'London',
          ml: 'ലണ്ടൻ',
          mt: 'Londra',
          pa: 'ਲੰਡਨ',
          ur: 'علاقہ لندن',
          ps: 'لندن',
          ny: 'London',
          co: 'Londra',
          li: 'Londe',
          vi: 'Luân Đôn',
          bn: 'লন্ডন',
          ee: 'London',
          fi: 'Lontoo',
          th: 'ลอนดอน',
          wo: 'Londar',
          ar: 'لندن',
          zu: 'ILondon',
          mr: 'लंडन',
          ha: 'Landan',
          lo: 'ລອນດອນ',
          gd: 'Lunnainn',
          te: 'లండన్',
          vo: 'London',
          fy: 'Londen',
          cv: 'Лондон',
          ja: 'ロンドン',
          fo: 'London',
          feature_name: 'London',
          am: 'ለንደን',
          kw: 'Loundres',
          fr: 'Londres',
          ia: 'London',
          uz: 'London',
          su: 'London',
          hy: 'Լոնդոն',
          mk: 'Лондон',
          tl: 'Londres',
          ig: 'London',
          fa: 'لندن',
          id: 'London',
          uk: 'Лондон',
          pt: 'Londres',
          oc: 'Londres',
          ko: '런던',
          tk: 'London',
          na: 'London',
          bm: 'London',
          sn: 'London',
          qu: 'London',
          to: 'Lonitoni',
          no: 'London',
          se: 'London',
          fj: 'Lodoni',
          ca: 'Londres',
          sh: 'London',
          ln: 'Lóndɛlɛ',
          wa: 'Londe',
          bi: 'London',
          cy: 'Llundain',
          yi: 'לאנדאן',
          tr: 'Londra',
          nv: 'Tooh Dineʼé Bikin Haalʼá',
          ky: 'Лондон',
          sw: 'London',
          ht: 'Lonn',
          hr: 'London',
          en: 'London',
          sq: 'Londra',
          gl: 'Londres',
          sv: 'London',
          bs: 'London',
          el: 'Λονδίνο',
          be: 'Лондан',
          sl: 'London',
          st: 'London',
          he: 'לונדון',
          ms: 'London',
          kl: 'London',
          et: 'London',
          tt: 'Лондон',
          lb: 'London',
          af: 'Londen',
          sm: 'Lonetona',
          an: 'Londres',
          ka: 'ლონდონი',
          bh: 'लंदन',
          ff: 'London',
          ug: 'لوندۇن',
          sa: 'लन्डन्',
          gv: 'Lunnin',
          kn: 'ಲಂಡನ್',
          jv: 'London',
          eo: 'Londono',
          nn: 'London',
          pl: 'Londyn',
          sk: 'Londýn',
          bo: 'ལོན་ཊོན།',
          om: 'Landan',
          de: 'London',
          sr: 'Лондон',
          hi: 'लंदन',
          gu: 'લંડન',
          lt: 'Londonas',
          gn: 'Lóndyre',
          lv: 'Londona',
          nl: 'Londen',
          ce: 'Лондон',
          it: 'Londra',
          ab: 'Лондон',
          mn: 'Лондон',
          so: 'London',
          my: 'လန်ဒန်မြို့',
          az: 'London',
          km: 'ឡុងដ៍',
          da: 'London',
          tg: 'Лондон',
          ro: 'Londra',
          kk: 'Лондон',
          av: 'Лондон',
          cu: 'Лондонъ',
          ga: 'Londain',
          cs: 'Londýn',
          sd: 'لنڊن',
          br: 'Londrez',
          tw: 'London',
          si: 'ලන්ඩන්',
          ascii: 'London',
          zh: '伦敦',
          bg: 'Лондон',
          io: 'London',
          mg: 'Lôndôna',
          ba: 'Лондон',
          es: 'Londres',
        },
        lat: 51.5073219,
        lon: -0.1276474,
        country: 'GB',
        state: 'England',
      },
      {
        name: 'City of London',
        local_names: {
          fr: 'Cité de Londres',
          zh: '倫敦市',
          ko: '시티 오브 런던',
          es: 'City de Londres',
          uk: 'Лондонське Сіті',
          lt: 'Londono Sitis',
          en: 'City of London',
          pt: 'Cidade de Londres',
          ru: 'Сити',
          hi: 'सिटी ऑफ़ लंदन',
          ur: 'لندن شہر',
          he: 'הסיטי של לונדון',
        },
        lat: 51.5156177,
        lon: -0.0919983,
        country: 'GB',
        state: 'England',
      },
      {
        name: 'London',
        local_names: {
          ko: '런던',
          ru: 'Лондон',
          he: 'לונדון',
          fa: 'لندن',
          ug: 'لوندۇن',
          ja: 'ロンドン',
          iu: 'ᓚᓐᑕᓐ',
          en: 'London',
          cr: 'ᓬᐊᐣᑕᐣ',
          fr: 'London',
          hy: 'Լոնտոն',
          oj: 'Baketigweyaang',
          lv: 'Landona',
          be: 'Лондан',
          yi: 'לאנדאן',
          th: 'ลอนดอน',
          bn: 'লন্ডন',
          ka: 'ლონდონი',
          lt: 'Londonas',
          ga: 'Londain',
          ar: 'لندن',
          el: 'Λόντον',
        },
        lat: 42.9832406,
        lon: -81.243372,
        country: 'CA',
        state: 'Ontario',
      },
      {
        name: 'Chelsea',
        local_names: {
          hu: 'Chelsea',
          he: "צ'לסי",
          da: 'Chelsea',
          zh: '車路士',
          es: 'Chelsea',
          sk: 'Chelsea',
          ru: 'Челси',
          eu: 'Chelsea',
          hi: 'चेल्सी, लंदन',
          it: 'Chelsea',
          uk: 'Челсі',
          fr: 'Chelsea',
          nl: 'Chelsea',
          en: 'Chelsea',
          vi: 'Chelsea, Luân Đôn',
          el: 'Τσέλσι',
          fa: 'چلسی',
          ko: '첼시',
          de: 'Chelsea',
          ga: 'Chelsea',
          az: 'Çelsi',
          no: 'Chelsea',
          sh: 'Chelsea, London',
          et: 'Chelsea',
          ar: 'تشيلسي',
          sv: 'Chelsea, London',
          ur: 'چیلسی، لندن',
          ja: 'チェルシー',
          pt: 'Chelsea',
          id: 'Chelsea, London',
          af: 'Chelsea, Londen',
          tr: 'Chelsea, Londra',
          pl: 'Chelsea',
        },
        lat: 51.4875167,
        lon: -0.1687007,
        country: 'GB',
        state: 'England',
      },
      {
        name: 'London',
        lat: 37.1289771,
        lon: -84.0832646,
        country: 'US',
        state: 'Kentucky',
      },
    ],
    selectedCity: 'London',
    weatherForecast: {
      lat: 51.5073,
      lon: -0.1276,
      timezone: 'Europe/London',
      timezone_offset: 3600,
      current: {
        dt: 1664157627,
        sunrise: 1664171561,
        sunset: 1664214665,
        temp: 11.38,
        feels_like: 10.56,
        pressure: 1006,
        humidity: 76,
        dew_point: 7.31,
        uvi: 0,
        clouds: 96,
        visibility: 10000,
        wind_speed: 6.17,
        wind_deg: 240,
        weather: [
          {
            id: 804,
            main: 'Clouds',
            description: 'overcast clouds',
            icon: '04n',
          },
        ],
      },
      hourly: [
        {
          dt: 1664157600,
          temp: 11.38,
          feels_like: 10.56,
          pressure: 1006,
          humidity: 76,
          dew_point: 7.31,
          uvi: 0,
          clouds: 96,
          visibility: 10000,
          wind_speed: 5.26,
          wind_deg: 237,
          wind_gust: 13.18,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.31,
        },
        {
          dt: 1664161200,
          temp: 11.3,
          feels_like: 10.52,
          pressure: 1006,
          humidity: 78,
          dew_point: 7.61,
          uvi: 0,
          clouds: 96,
          visibility: 8686,
          wind_speed: 5.38,
          wind_deg: 233,
          wind_gust: 13.41,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.71,
        },
        {
          dt: 1664164800,
          temp: 11.22,
          feels_like: 10.54,
          pressure: 1005,
          humidity: 82,
          dew_point: 8.26,
          uvi: 0,
          clouds: 97,
          visibility: 10000,
          wind_speed: 5.98,
          wind_deg: 230,
          wind_gust: 14.11,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.74,
        },
        {
          dt: 1664168400,
          temp: 11.44,
          feels_like: 10.86,
          pressure: 1004,
          humidity: 85,
          dew_point: 9.01,
          uvi: 0,
          clouds: 97,
          visibility: 10000,
          wind_speed: 5.93,
          wind_deg: 236,
          wind_gust: 13.58,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10n',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.74,
          },
        },
        {
          dt: 1664172000,
          temp: 11.92,
          feels_like: 11.49,
          pressure: 1002,
          humidity: 89,
          dew_point: 10.17,
          uvi: 0,
          clouds: 98,
          visibility: 10000,
          wind_speed: 5.51,
          wind_deg: 244,
          wind_gust: 12.89,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 1,
          rain: {
            '1h': 0.25,
          },
        },
        {
          dt: 1664175600,
          temp: 12.97,
          feels_like: 12.62,
          pressure: 1001,
          humidity: 88,
          dew_point: 10.99,
          uvi: 0.14,
          clouds: 100,
          visibility: 9839,
          wind_speed: 5.46,
          wind_deg: 294,
          wind_gust: 10.96,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 0.82,
          rain: {
            '1h': 0.53,
          },
        },
        {
          dt: 1664179200,
          temp: 12.22,
          feels_like: 11.48,
          pressure: 1002,
          humidity: 76,
          dew_point: 8.17,
          uvi: 0.51,
          clouds: 100,
          visibility: 10000,
          wind_speed: 4.91,
          wind_deg: 317,
          wind_gust: 10.4,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 0.89,
          rain: {
            '1h': 0.39,
          },
        },
        {
          dt: 1664182800,
          temp: 12.93,
          feels_like: 12.13,
          pressure: 1002,
          humidity: 71,
          dew_point: 7.77,
          uvi: 1.15,
          clouds: 81,
          visibility: 10000,
          wind_speed: 5.34,
          wind_deg: 315,
          wind_gust: 10.06,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.77,
        },
        {
          dt: 1664186400,
          temp: 13.63,
          feels_like: 12.75,
          pressure: 1002,
          humidity: 65,
          dew_point: 7.21,
          uvi: 1.11,
          clouds: 65,
          visibility: 10000,
          wind_speed: 6.38,
          wind_deg: 316,
          wind_gust: 10.17,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.84,
        },
        {
          dt: 1664190000,
          temp: 13.55,
          feels_like: 12.61,
          pressure: 1002,
          humidity: 63,
          dew_point: 6.69,
          uvi: 1.48,
          clouds: 72,
          visibility: 10000,
          wind_speed: 6.12,
          wind_deg: 315,
          wind_gust: 10.49,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 0.81,
          rain: {
            '1h': 0.25,
          },
        },
        {
          dt: 1664193600,
          temp: 14.23,
          feels_like: 13.07,
          pressure: 1002,
          humidity: 52,
          dew_point: 4.64,
          uvi: 1.63,
          clouds: 72,
          visibility: 10000,
          wind_speed: 6.12,
          wind_deg: 329,
          wind_gust: 9.04,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.76,
        },
        {
          dt: 1664197200,
          temp: 13.84,
          feels_like: 12.74,
          pressure: 1002,
          humidity: 56,
          dew_point: 5.08,
          uvi: 1.62,
          clouds: 99,
          visibility: 10000,
          wind_speed: 5.6,
          wind_deg: 342,
          wind_gust: 8.86,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0.02,
        },
        {
          dt: 1664200800,
          temp: 13.75,
          feels_like: 12.51,
          pressure: 1003,
          humidity: 51,
          dew_point: 3.83,
          uvi: 1.23,
          clouds: 99,
          visibility: 10000,
          wind_speed: 5.39,
          wind_deg: 337,
          wind_gust: 8.62,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0.02,
        },
        {
          dt: 1664204400,
          temp: 13.29,
          feels_like: 12.08,
          pressure: 1003,
          humidity: 54,
          dew_point: 4.22,
          uvi: 0.76,
          clouds: 99,
          visibility: 10000,
          wind_speed: 5.51,
          wind_deg: 325,
          wind_gust: 8.68,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664208000,
          temp: 13.14,
          feels_like: 11.84,
          pressure: 1004,
          humidity: 51,
          dew_point: 3.17,
          uvi: 0.3,
          clouds: 99,
          visibility: 10000,
          wind_speed: 4.78,
          wind_deg: 325,
          wind_gust: 9.04,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664211600,
          temp: 13.14,
          feels_like: 11.76,
          pressure: 1004,
          humidity: 48,
          dew_point: 2.17,
          uvi: 0.09,
          clouds: 88,
          visibility: 10000,
          wind_speed: 4.62,
          wind_deg: 322,
          wind_gust: 9.74,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664215200,
          temp: 12.56,
          feels_like: 11.18,
          pressure: 1005,
          humidity: 50,
          dew_point: 2.36,
          uvi: 0,
          clouds: 90,
          visibility: 10000,
          wind_speed: 4.55,
          wind_deg: 317,
          wind_gust: 9.82,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664218800,
          temp: 12.18,
          feels_like: 10.81,
          pressure: 1005,
          humidity: 52,
          dew_point: 2.61,
          uvi: 0,
          clouds: 95,
          visibility: 10000,
          wind_speed: 4.53,
          wind_deg: 314,
          wind_gust: 8.89,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664222400,
          temp: 11.37,
          feels_like: 10.08,
          pressure: 1006,
          humidity: 58,
          dew_point: 3.28,
          uvi: 0,
          clouds: 90,
          visibility: 10000,
          wind_speed: 4.53,
          wind_deg: 304,
          wind_gust: 8.23,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664226000,
          temp: 10.87,
          feels_like: 9.63,
          pressure: 1006,
          humidity: 62,
          dew_point: 3.76,
          uvi: 0,
          clouds: 64,
          visibility: 10000,
          wind_speed: 4.46,
          wind_deg: 301,
          wind_gust: 8.88,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664229600,
          temp: 10.41,
          feels_like: 9.15,
          pressure: 1006,
          humidity: 63,
          dew_point: 3.57,
          uvi: 0,
          clouds: 48,
          visibility: 10000,
          wind_speed: 4.42,
          wind_deg: 294,
          wind_gust: 9.78,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664233200,
          temp: 10.15,
          feels_like: 8.87,
          pressure: 1006,
          humidity: 63,
          dew_point: 3.4,
          uvi: 0,
          clouds: 47,
          visibility: 10000,
          wind_speed: 4.48,
          wind_deg: 291,
          wind_gust: 9.92,
          weather: [
            {
              id: 802,
              main: 'Clouds',
              description: 'scattered clouds',
              icon: '03n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664236800,
          temp: 10.07,
          feels_like: 8.86,
          pressure: 1006,
          humidity: 66,
          dew_point: 3.85,
          uvi: 0,
          clouds: 56,
          visibility: 10000,
          wind_speed: 3.53,
          wind_deg: 288,
          wind_gust: 8.91,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664240400,
          temp: 10.17,
          feels_like: 9.04,
          pressure: 1006,
          humidity: 69,
          dew_point: 4.72,
          uvi: 0,
          clouds: 91,
          visibility: 10000,
          wind_speed: 3.65,
          wind_deg: 275,
          wind_gust: 9.38,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664244000,
          temp: 10.24,
          feels_like: 9.23,
          pressure: 1005,
          humidity: 73,
          dew_point: 5.56,
          uvi: 0,
          clouds: 89,
          visibility: 10000,
          wind_speed: 5.14,
          wind_deg: 281,
          wind_gust: 9.28,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.02,
        },
        {
          dt: 1664247600,
          temp: 10.35,
          feels_like: 9.27,
          pressure: 1005,
          humidity: 70,
          dew_point: 5.18,
          uvi: 0,
          clouds: 93,
          visibility: 10000,
          wind_speed: 4.29,
          wind_deg: 287,
          wind_gust: 8.63,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664251200,
          temp: 10.09,
          feels_like: 9.11,
          pressure: 1005,
          humidity: 75,
          dew_point: 5.93,
          uvi: 0,
          clouds: 95,
          visibility: 10000,
          wind_speed: 4.18,
          wind_deg: 282,
          wind_gust: 8.76,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.02,
        },
        {
          dt: 1664254800,
          temp: 9.9,
          feels_like: 8,
          pressure: 1004,
          humidity: 76,
          dew_point: 5.82,
          uvi: 0,
          clouds: 96,
          visibility: 10000,
          wind_speed: 3.75,
          wind_deg: 272,
          wind_gust: 7.56,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0.02,
        },
        {
          dt: 1664258400,
          temp: 9.73,
          feels_like: 7.78,
          pressure: 1004,
          humidity: 77,
          dew_point: 5.83,
          uvi: 0,
          clouds: 96,
          visibility: 10000,
          wind_speed: 3.76,
          wind_deg: 263,
          wind_gust: 8.91,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0.02,
        },
        {
          dt: 1664262000,
          temp: 9.75,
          feels_like: 7.6,
          pressure: 1004,
          humidity: 78,
          dew_point: 5.97,
          uvi: 0.05,
          clouds: 100,
          visibility: 10000,
          wind_speed: 4.21,
          wind_deg: 267,
          wind_gust: 10.15,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664265600,
          temp: 10.51,
          feels_like: 9.55,
          pressure: 1004,
          humidity: 74,
          dew_point: 5.99,
          uvi: 0.18,
          clouds: 100,
          visibility: 10000,
          wind_speed: 4.76,
          wind_deg: 274,
          wind_gust: 9.9,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0.14,
        },
        {
          dt: 1664269200,
          temp: 12.04,
          feels_like: 10.94,
          pressure: 1004,
          humidity: 63,
          dew_point: 5.18,
          uvi: 0.42,
          clouds: 83,
          visibility: 10000,
          wind_speed: 5.53,
          wind_deg: 286,
          wind_gust: 10.07,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.11,
        },
        {
          dt: 1664272800,
          temp: 13.54,
          feels_like: 12.31,
          pressure: 1003,
          humidity: 52,
          dew_point: 3.88,
          uvi: 1.45,
          clouds: 66,
          visibility: 10000,
          wind_speed: 5.37,
          wind_deg: 288,
          wind_gust: 8.52,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.11,
        },
        {
          dt: 1664276400,
          temp: 14.57,
          feels_like: 13.28,
          pressure: 1002,
          humidity: 46,
          dew_point: 2.93,
          uvi: 1.94,
          clouds: 66,
          visibility: 10000,
          wind_speed: 5.55,
          wind_deg: 293,
          wind_gust: 9.01,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.1,
        },
        {
          dt: 1664280000,
          temp: 14.62,
          feels_like: 13.44,
          pressure: 1002,
          humidity: 50,
          dew_point: 4.31,
          uvi: 2.12,
          clouds: 69,
          visibility: 10000,
          wind_speed: 5.83,
          wind_deg: 279,
          wind_gust: 9.17,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.11,
        },
        {
          dt: 1664283600,
          temp: 15.19,
          feels_like: 14.04,
          pressure: 1001,
          humidity: 49,
          dew_point: 4.35,
          uvi: 2.01,
          clouds: 81,
          visibility: 10000,
          wind_speed: 5.5,
          wind_deg: 286,
          wind_gust: 9.52,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          pop: 0.56,
          rain: {
            '1h': 0.13,
          },
        },
        {
          dt: 1664287200,
          temp: 15.21,
          feels_like: 14.01,
          pressure: 1001,
          humidity: 47,
          dew_point: 3.87,
          uvi: 1.52,
          clouds: 81,
          visibility: 10000,
          wind_speed: 5.8,
          wind_deg: 278,
          wind_gust: 8.46,
          weather: [
            {
              id: 803,
              main: 'Clouds',
              description: 'broken clouds',
              icon: '04d',
            },
          ],
          pop: 0.54,
        },
        {
          dt: 1664290800,
          temp: 14.16,
          feels_like: 12.88,
          pressure: 1000,
          humidity: 48,
          dew_point: 3.26,
          uvi: 0.93,
          clouds: 87,
          visibility: 10000,
          wind_speed: 4.88,
          wind_deg: 288,
          wind_gust: 9.06,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0.26,
        },
        {
          dt: 1664294400,
          temp: 14.39,
          feels_like: 13.03,
          pressure: 1000,
          humidity: 44,
          dew_point: 2.33,
          uvi: 0.36,
          clouds: 88,
          visibility: 10000,
          wind_speed: 4.53,
          wind_deg: 293,
          wind_gust: 9.97,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0.06,
        },
        {
          dt: 1664298000,
          temp: 13.94,
          feels_like: 12.59,
          pressure: 1000,
          humidity: 46,
          dew_point: 2.4,
          uvi: 0.11,
          clouds: 90,
          visibility: 10000,
          wind_speed: 3.21,
          wind_deg: 273,
          wind_gust: 8.92,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04d',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664301600,
          temp: 13.64,
          feels_like: 12.34,
          pressure: 1000,
          humidity: 49,
          dew_point: 2.95,
          uvi: 0,
          clouds: 92,
          visibility: 10000,
          wind_speed: 3.35,
          wind_deg: 280,
          wind_gust: 8.74,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664305200,
          temp: 13.03,
          feels_like: 11.85,
          pressure: 999,
          humidity: 56,
          dew_point: 4.29,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 3.07,
          wind_deg: 274,
          wind_gust: 7.42,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664308800,
          temp: 12.62,
          feels_like: 11.56,
          pressure: 999,
          humidity: 62,
          dew_point: 5.62,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 3.03,
          wind_deg: 277,
          wind_gust: 7.17,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664312400,
          temp: 12.06,
          feels_like: 11.04,
          pressure: 999,
          humidity: 66,
          dew_point: 5.85,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.71,
          wind_deg: 285,
          wind_gust: 6.96,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664316000,
          temp: 11.86,
          feels_like: 10.8,
          pressure: 999,
          humidity: 65,
          dew_point: 5.51,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.6,
          wind_deg: 288,
          wind_gust: 6.75,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664319600,
          temp: 11.57,
          feels_like: 10.48,
          pressure: 998,
          humidity: 65,
          dew_point: 5.12,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.7,
          wind_deg: 293,
          wind_gust: 6.88,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664323200,
          temp: 11.31,
          feels_like: 10.19,
          pressure: 998,
          humidity: 65,
          dew_point: 4.82,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 2.87,
          wind_deg: 290,
          wind_gust: 7.46,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
        {
          dt: 1664326800,
          temp: 10.9,
          feels_like: 9.8,
          pressure: 998,
          humidity: 67,
          dew_point: 4.94,
          uvi: 0,
          clouds: 100,
          visibility: 10000,
          wind_speed: 3.14,
          wind_deg: 297,
          wind_gust: 7.72,
          weather: [
            {
              id: 804,
              main: 'Clouds',
              description: 'overcast clouds',
              icon: '04n',
            },
          ],
          pop: 0,
        },
      ],
      daily: [
        {
          dt: 1664190000,
          sunrise: 1664171561,
          sunset: 1664214665,
          moonrise: 1664172780,
          moonset: 1664216220,
          moon_phase: 0.02,
          temp: {
            day: 13.55,
            min: 10.41,
            max: 14.23,
            night: 10.41,
            eve: 13.14,
            morn: 11.44,
          },
          feels_like: {
            day: 12.61,
            night: 9.15,
            eve: 11.76,
            morn: 10.86,
          },
          pressure: 1002,
          humidity: 63,
          dew_point: 6.69,
          wind_speed: 6.38,
          wind_deg: 316,
          wind_gust: 14.11,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 72,
          pop: 1,
          rain: 2.16,
          uvi: 1.63,
        },
        {
          dt: 1664276400,
          sunrise: 1664258057,
          sunset: 1664300926,
          moonrise: 1664263860,
          moonset: 1664303460,
          moon_phase: 0.05,
          temp: {
            day: 14.57,
            min: 9.73,
            max: 15.21,
            night: 11.86,
            eve: 13.94,
            morn: 9.9,
          },
          feels_like: {
            day: 13.28,
            night: 10.8,
            eve: 12.59,
            morn: 8,
          },
          pressure: 1002,
          humidity: 46,
          dew_point: 2.93,
          wind_speed: 5.83,
          wind_deg: 279,
          wind_gust: 10.15,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 66,
          pop: 0.56,
          rain: 0.13,
          uvi: 2.12,
        },
        {
          dt: 1664362800,
          sunrise: 1664344554,
          sunset: 1664387188,
          moonrise: 1664355120,
          moonset: 1664390760,
          moon_phase: 0.09,
          temp: {
            day: 14.11,
            min: 8.84,
            max: 14.8,
            night: 12.5,
            eve: 13.8,
            morn: 9.21,
          },
          feels_like: {
            day: 12.78,
            night: 11.22,
            eve: 12.41,
            morn: 7.08,
          },
          pressure: 998,
          humidity: 46,
          dew_point: 2.7,
          wind_speed: 4.71,
          wind_deg: 311,
          wind_gust: 9.9,
          weather: [
            {
              id: 800,
              main: 'Clear',
              description: 'clear sky',
              icon: '01d',
            },
          ],
          clouds: 6,
          pop: 0,
          uvi: 2.15,
        },
        {
          dt: 1664449200,
          sunrise: 1664431050,
          sunset: 1664473449,
          moonrise: 1664446560,
          moonset: 1664478360,
          moon_phase: 0.12,
          temp: {
            day: 15.42,
            min: 8.79,
            max: 15.96,
            night: 13.52,
            eve: 14.7,
            morn: 8.79,
          },
          feels_like: {
            day: 14.35,
            night: 12.49,
            eve: 13.51,
            morn: 7.76,
          },
          pressure: 1004,
          humidity: 51,
          dew_point: 5.19,
          wind_speed: 4.9,
          wind_deg: 355,
          wind_gust: 7.5,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 39,
          pop: 0.36,
          rain: 0.31,
          uvi: 2.45,
        },
        {
          dt: 1664535600,
          sunrise: 1664517547,
          sunset: 1664559711,
          moonrise: 1664538060,
          moonset: 1664566380,
          moon_phase: 0.16,
          temp: {
            day: 16.66,
            min: 10.42,
            max: 17.56,
            night: 13.9,
            eve: 14.87,
            morn: 10.42,
          },
          feels_like: {
            day: 15.63,
            night: 13.62,
            eve: 14.03,
            morn: 9.66,
          },
          pressure: 1013,
          humidity: 48,
          dew_point: 5.64,
          wind_speed: 7.09,
          wind_deg: 218,
          wind_gust: 15.41,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 58,
          pop: 0.98,
          rain: 1.6,
          uvi: 2.66,
        },
        {
          dt: 1664622000,
          sunrise: 1664604044,
          sunset: 1664645974,
          moonrise: 1664629440,
          moonset: 1664655060,
          moon_phase: 0.19,
          temp: {
            day: 19.21,
            min: 14.68,
            max: 21.16,
            night: 17.95,
            eve: 18.36,
            morn: 16.53,
          },
          feels_like: {
            day: 19.25,
            night: 17.5,
            eve: 18.05,
            morn: 16.67,
          },
          pressure: 1016,
          humidity: 79,
          dew_point: 15.44,
          wind_speed: 8.24,
          wind_deg: 231,
          wind_gust: 17.45,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 94,
          pop: 1,
          rain: 2.27,
          uvi: 3,
        },
        {
          dt: 1664708400,
          sunrise: 1664690542,
          sunset: 1664732236,
          moonrise: 1664720220,
          moonset: 1664744760,
          moon_phase: 0.23,
          temp: {
            day: 20.56,
            min: 16.92,
            max: 20.56,
            night: 17.02,
            eve: 17.78,
            morn: 17.46,
          },
          feels_like: {
            day: 20.26,
            night: 17.13,
            eve: 17.86,
            morn: 17.32,
          },
          pressure: 1025,
          humidity: 61,
          dew_point: 12.72,
          wind_speed: 6.33,
          wind_deg: 246,
          wind_gust: 14.12,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 92,
          pop: 0.32,
          rain: 1.05,
          uvi: 3,
        },
        {
          dt: 1664794800,
          sunrise: 1664777040,
          sunset: 1664818499,
          moonrise: 1664810040,
          moonset: 1664835480,
          moon_phase: 0.25,
          temp: {
            day: 19.76,
            min: 16.45,
            max: 21.32,
            night: 17.11,
            eve: 19.28,
            morn: 16.45,
          },
          feels_like: {
            day: 19.67,
            night: 16.91,
            eve: 19.14,
            morn: 16.5,
          },
          pressure: 1026,
          humidity: 72,
          dew_point: 14.45,
          wind_speed: 2.19,
          wind_deg: 213,
          wind_gust: 4.62,
          weather: [
            {
              id: 500,
              main: 'Rain',
              description: 'light rain',
              icon: '10d',
            },
          ],
          clouds: 99,
          pop: 0.2,
          rain: 0.15,
          uvi: 3,
        },
      ],
    },
  },
};
